"""create jobs table

Revision ID: a60ec8377015
Revises: 9b8bc18f68c4
Create Date: 2026-09-10 22:27:34.851741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a60ec8377015'
down_revision: Union[str, Sequence[str], None] = '9b8bc18f68c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_document_id', sa.UUID(), nullable=False),
    sa.Column('extractor', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('company', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publisher', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requested_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
